### ISSUE TITLE
Update external landing page

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#14]

**Comment by ERThompson765** [comment]
https://docs.google.com/document/d/1tZZuYP_IyR7CuTazmwV7MT3O7VMo6fkxTx-n4ySkEPg/edit

**Comment by sbrunswi** [comment]
- [ ] Update text in a google docs: 1) add the Protect Purdue logo 2) update dates
- [ ] share google docs and logo goes to the firebase!

**Comment by sbrunswi** [comment]
https://docs.google.com/document/d/1mrmeTny72b1lLoYxR-1zMuoIavVPPTET6y7NMrYHcFo/edit (not yet edited); use review feature in change track so that matt sees what has been changed

**Comment by ERThompson765** [comment]
Update with track changes have been made. Ready for further discussion and adjustment https://docs.google.com/document/d/1mrmeTny72b1lLoYxR-1zMuoIavVPPTET6y7NMrYHcFo/edit?usp=sharing

**Comment by sbrunswi** [comment]
Since we have another issue on this I am closing this
