### ISSUE TITLE
MONDAY MEETING

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#15]
Preparation of slides 

@ERThompson765  - these are your task! 

Section Protect Purdue Hack Slides 
- [ ] Slide on timeline (based on template from music challenge)
- [x] Slide on target audience and recruitment goals: Use the sampling plan we had: Minimum-skill level, Purdue affiliated preferred but can also be from outside, and one more thing (Check doc) and target (100 to participate, meaning we need a lot of sign-ups; based on the sampling results from pilot) 
- [x] Slide on benefits for the participants: - pull out old benefits and check the proposal (increase their awareness of COVID-19 risk and pay attention to Protect Purdue Policy)
- [x] Slide benefits for faculty: 1) Extra credits, or credits for student project, 2) Access to results of their results, 3) Opportunity collaborate on using Safegraph data, 4) Opportunity learn about Ironhacks platform and using for other challenges 
- [x] Policy implications ...

#### below are notes that are more broadly ####

- [x] Task development/description
- [x] Data pre-processing (parsing data/sites - Mai??)
- [x] Understanding task - knowledge sharing and collective incentives
- [x] Sampling and recruiting plan
- [x] Github issues cleanup
- [x] Elizabeth finalize process and add key calendar dates (for discussion with profs)

**Comment by ERThompson765** [comment]
Should we retitle this as there are still important recruiting details and parts of the setup/launch process that are not yet completed

**Comment by sbrunswi** [comment]
I am closing this issue as the meeting is done! However, there are a range of individual action items still open.
