### ISSUE TITLE
Internal landing page content

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#19]
Updating content of the internal landing page. Information can be viewed here: https://docs.google.com/document/d/137lx3L45vWJrzZkgCeb_ZuZxHHTRogoF2YTcLWr-GU0/edit?usp=sharing

**Comment by sbrunswi** [comment]
Disclaimer: We need a statement that says that we need at least 60 participants!

**Comment by Amel-Chekili** [comment]
Changed CDC news link to CDC link: https://www.cdc.gov/coronavirus/2019-nCoV/index.html. The one that was previously used was https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/cloth-face-cover-guidance.html it focused on wearing masks which I think isn't relevant to the challenge. There is also this CDC page that explain the importance of social distancing that we can consider but it is not news https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/social-distancing.html

For Python internal page
1. changed the tutorial link to https://ironhacks.com/hacks/covid-19-data-science-challenge-fall-2020-to-protect-purdue-python/tutorials
2. link of Rules: the pages shows the statement "not available yet" https://ironhacks.com/hacks/covid-19-data-science-challenge-fall-2020-to-protect-purdue-python/rules
3. link of Task statement: the pages show the statement "not available yet" https://ironhacks.com/hacks/covid-19-data-science-challenge-fall-2020-to-protect-purdue-python/task

For R:
1. link of Task statement link lead to a blank page https://ironhacks.com/hacks/covid-19-data-science-challenge-fall-2020-to-protect-purdue-r/task
2. Link of Rules: page shows the statement Rules not available yet https://ironhacks.com/hacks/covid-19-data-science-challenge-fall-2020-to-protect-purdue-r/rules
3. Under the section Questions?
There you find announcements. You can also contact us by clicking on Get in touch in the upper right corner.
there is a link that opens directly the teams email while this link doesn't exist in the same section in python internal page

**Comment by sbrunswi** [comment]
I have closed this issue and opened a new one as I have reworked the internal page again. There is lack of diligence @ERThompson765
