### ISSUE TITLE
Set goals for new sampling doc

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#21]
Note population numbers and outreach channels to set goals for 100 participants

**Comment by sbrunswi** [comment]
https://docs.google.com/document/d/1XiAUQLUciTAkAdj_DI2i23m-GzzbFSO60NPIPywE19s/edit#

**Comment by ERThompson765** [comment]
It would be useful to do a review of the sampling and recruiting process and create a formalized process document template that could be used for future hacks.

Additional attention could be put on how to recruit people to the platform generally, and not just for a specific hack, such that they get engaged in the demo or other "ongoing" hacks similar to Kaggle to help create the critical mass needed more easily for future hacks
