### ISSUE TITLE
Update registration survey

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#24]
@ERThompson765  never add an empty issue! So what needs to be updated? This should be done by tonight and also coordinated with Matt @charrismatic!

**Comment by sbrunswi** [comment]
@ERThompson765 @charrismatic  I assume this is done! Did you please test last night!

**Comment by ERThompson765** [comment]
This was reviewed last night. And I confirm the correct link and survey are added to both hacks. I went through both of them today as I registered, so this issue is resolved.
