### ISSUE TITLE
Emailing - recruiting progress

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#28]
- [x] Emails to GitHub populations
- [x] Follow up emails to professors
- [x] Note here other contacts needed ____________________
- [x] Need an email finished for users not yet registered to Hack

See spreadsheet notes for additional details

**Comment by ERThompson765** [comment]
Prof Ming from our new professors sheet had sent an update to students. It is possible that is one to two of the recently registered. I have created drafts of both "Next Steps" for registered to hack, and also now created a start of a draft for those users who are not yet registered

**Comment by sbrunswi** [comment]
I think we have to add some additional to dos here
- [x] second email to advisors should be drafted to be sent
- [x] second email for Melissa to be drafted upon feedback from Melissa @Amel-Chekili 
- [x] Email for Ann Majchrzak/other external partners @Amel-Chekili 
- [x] Send email to Alok @sbrunswi 
- [x] Send email to Sorin
- [x] Send email to all clubs again upon coordination with Elizabeth

**Comment by sbrunswi** [comment]
@ERThompson765  can you send to Ann or should I do it?

**Comment by sbrunswi** [comment]
@ERThompson765  Sorin needs a follow up!
