### ISSUE TITLE
Pre survey updates

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#29]
Review and update

Degree of cooperativeness (individual differences... pull from post survey)
psychological safety
Aspiration

**Comment by ERThompson765** [comment]
@sbrunswi  @Amel-Chekili the Protect Purdue pre-survey has been updated. I think maybe the consent form link needs reviewed that it works and/or needs some minor wording updates

**Comment by sbrunswi** [comment]
1) Adjusting the MSPE in the survey based on data from the pilot hack!

**Comment by ERThompson765** [comment]
@sbrunswi the survey is updated with the performance criteria and other edits. Please see my notes in the survey.

**Comment by ERThompson765** [comment]
@sbrunswi sbrunswi Survey is updated as of 12/6/2020 with flexibility scale
