### ISSUE TITLE
Remove bug on website: www.rcodi.org

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#30]
A critical error shows when trying to log in to admin. This happens also when trying to access via Bluehost

**Comment by sbrunswi** [comment]
@jialincheoh  please take on this challenge and complete it.

**Comment by ERThompson765** [comment]
@jialincheoh @charrismatic we have discussed that the site will need taken down for a short period to be able to complete the fix. In speaking with @sbrunswi I communicated this information and also that as a group we thought it would be best to wait until after the hack is completed, as well as confirmation from Prof. Sabine regarding any grants in progress which might hinder those opportunities if reviewers cannot access the public facing website.
