### ISSUE TITLE
Forum Posts December 13-17

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#33]
Forum posts completed each day through the remainder of the competition:

- [x] Saturday - amal post on deadline 2
- [ ] Sunday - content post/reminder deadline 3
- [ ] Monday - content post/reminder deadline 4
- [ ] Tuesday - content post/reminder deadline 5
- [ ] Wednesday - content post/reminder deadline 6
- [ ] Thursday - submission deadline noon post (early a.m.)

**Comment by sbrunswi** [comment]
@ERThompson765 what do we do this?
