### ISSUE TITLE
Winner payments

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#34]
Get final scores
Add details to business office sheet (See Drive)
Get this completed by 12pm Friday 18th

**Comment by sbrunswi** [comment]
Here is the template for the payment! https://drive.google.com/file/d/1N-7XaYgK71dXT79bABsvDerb2gAoNXzZ/view?usp=sharing

**Comment by sbrunswi** [comment]
@ERThompson765  https://docs.google.com/spreadsheets/d/1N-7XaYgK71dXT79bABsvDerb2gAoNXzZ/edit#gid=1402274755 we can already fill in the names of the 10 people that have submitted two times!
