### ISSUE TITLE
Abstract publication deadline

### ISSUE THREAD

**Issue by ERThompson765** [ironhacks/ironhacks-org#41]
- [ ] Mai and Prof. Sabine to discuss outline/format after Friday March 4

- [ ] Elizabeth working on theoretical/qualitative components

**Comment by sbrunswi** [comment]
@ERThompson765  we have successfully submitted to CI (Mai, Feny, and I) - not sure what this is about! So I am closing this but you should open a new one for CSCW for the qualitative analysis.
