### ISSUE TITLE
Report partners involved in COVID-19 August 2020 Hack

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhacks-org#6]
- [x] follow the structure from the NSF report. See https://www.dropbox.com/s/oiraga2b03a13pt/RPPR%20-%20Preview%20Report.pdf?dl=0 
- [x] A sheet/table is good to start off or you put it into system directly using my log-in

**Comment by ERThompson765** [comment]
https://docs.google.com/spreadsheets/d/1C5jx3xv3kMqFtLbfM2RzB26LlPXydUbgVsxHI0odXPo/edit?usp=sharing
